[config]
reload_apps = true

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync-colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim-colors.lua'
output_path = '~/.config/nvim/lua/matugen-colors.lua'

[templates.cava]
input_path = "~/.config/matugen/templates/cava"
output_path = "~/.config/cava/config"

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.hyprland_lua]
input_path = '~/.config/matugen/templates/colors.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.codium]
input_path = '~/.config/matugen/templates/codium.json'
output_path = '~/.config/matugen/codium-colors.json'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock-colors.conf'
