$background = rgb({{colors.background.default.hex_stripped}})
$primary = rgb({{colors.primary.default.hex_stripped}})
$on_background = rgb({{colors.on_background.default.hex_stripped}})
$surface = rgb({{colors.surface.default.hex_stripped}})
$outline = rgb({{colors.outline.default.hex_stripped}})
